name: 'Delete Release Assets'
description: 'A simple GitHub action which deletes all assets attached to a release. It is mainly designed to make sure electron-builder does not fail upon a release.'
inputs:
  delete-only-drafts:
    description: 'Should we only delete assets from drafts?'
    required: true
    default: 'true'
  version:
    description: 'Which version should we delete the assets from?'
    required: true
    default: ''
  github-access-token:
    description: 'The GitHub access token required to delete the assets & discover non released versions'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
